on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: just a test message
        required: true
        default: testing

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: post to github api
        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
        # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
        run: |
          curl --location \
          --request POST \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ secrets.personal_access_token }}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ vars.target_repo_owner }}/${{ vars.target_repo_name }}/dispatches \
          --data '{"event_type":"manual-test","client_payload":{"message":"${{ github.event.inputs.message }}"}}'
